In [1]:
# default_exp core

# 42AI Machine Learning Bootcamp

> API details.

In [2]:
import numpy as np

In [3]:
def sum_(x, f):
    if not isinstance(x, np.ndarray) or x.size == 0 or x.ndim != 1 or not callable(f):
        return None
    result = 0.0
    for element in x:
        result += f(element)
    return result

In [4]:
# Sum
x = np.array([0, 15, -9, 7, 12, 3, -21])
print(sum_(x, lambda x: x))
print(sum_(x, lambda x: x**2))

7.0
949.0
7.0
949.0
7.0
949.0


In [5]:
def mean_(x):
    if not isinstance(x, np.ndarray) or x.size == 0 or x.ndim != 1:
        return None
    return sum_(x, lambda x: x) / x.size

In [6]:
# Mean
x = np.array([0, 15, -9, 7, 12, 3, -21])
print(mean_(x))
print(mean_(x ** 2))

1.0
135.57142857142858
1.0
135.57142857142858
1.0
135.57142857142858


In [7]:
def variance(x):
    if not isinstance(x, np.ndarray) or x.size == 0 or x.ndim != 1:
        return None
    return mean_((x - mean_(x))**2)

In [8]:
# Variance
x = np.array([0, 15, -9, 7, 12, 3, -21])
print(variance(x))
print(np.var(x))

print(variance(x/2))
print(np.var(x/2))

134.57142857142858
134.57142857142858
33.642857142857146
33.642857142857146
134.57142857142858
134.57142857142858
33.642857142857146
33.642857142857146
134.57142857142858
134.57142857142858
33.642857142857146
33.642857142857146


In [9]:
from math import sqrt


def std(x):
    if not isinstance(x, np.ndarray) or x.size == 0 or x.ndim != 1:
        return None
    return sqrt((variance(x)))

In [10]:
# Standard deviation
x = np.array([0, 15, -9, 7, 12, 3, -21])
y = np.array([2, 14, -13, 5, 12, 4, -19])

print(std(x))
print(np.std(x))

print(std(y))
print(np.std(y))

11.600492600378166
11.600492600378166
11.410700312980492
11.410700312980492
11.600492600378166
11.600492600378166
11.410700312980492
11.410700312980492
11.600492600378166
11.600492600378166
11.410700312980492
11.410700312980492


In [11]:
def dot(x, y):
    if (not isinstance(x, np.ndarray) or not isinstance(y, np.ndarray) or x.size == 0 
        or y.size == 0 or x.size != y.size or x.ndim != 1 or y.ndim != 1):
        print("Error: dot")
        return None
    result = 0
    for i in range(x.size):
        result += x[i] * y[i]
    return result

In [12]:
# Dot product
x = np.array([0, 15, -9, 7, 12, 3, -21])
y = np.array([2, 14, -13, 5, 12, 4, -19])

print(dot(x, y))
print(np.dot(x, y))

print(dot(x, x))
print(np.dot(x, x))

print(dot(y, y))
print(np.dot(y, y))

917
917
949
949
915
915
917
917
949
949
915
915
917
917
949
949
915
915


In [13]:
def mat_vec_prod(m, x):
    if (not isinstance(m, np.ndarray) or not isinstance(x, np.ndarray) or
            m.size == 0 or m.shape[1] != x.size):
        print("Error: mat_vec_prod")
        return None
    result = np.array([], dtype='int')
    for row in m:
        result = np.append(result, dot(x, row))
    return result.reshape((m.shape[0], 1))

In [14]:
# Matrix-vector product
m = np.array([
    [-8, 8, -6, 14, 14, -9, -4],
    [2, -11, -2, -11, 14, -2, 14],
    [-13, -2, -5, 3, -8, -4, 13],
    [2, 13, -14, -15, -14, -15, 13],
    [2, -1, 12, 3, -7, -3, -6]])
x = np.array([0, 15, -9, 7, 12, 3, -21]).reshape((7, 1))
y = np.array([2, 14, -13, 5, 12, 4, -19]).reshape((7, 1))

print(mat_vec_prod(m, x))
print(m.dot(x))

print(mat_vec_prod(m, y))
print(m.dot(y))

Error: dot
Error: dot
Error: dot
Error: dot
Error: dot
[[None]
 [None]
 [None]
 [None]
 [None]]
[[ 497]
 [-356]
 [-345]
 [-270]
 [ -69]]
Error: dot
Error: dot
Error: dot
Error: dot
Error: dot
[[None]
 [None]
 [None]
 [None]
 [None]]
[[ 452]
 [-285]
 [-333]
 [-182]
 [-133]]
Error: dot
Error: dot
Error: dot
Error: dot
Error: dot
[[None]
 [None]
 [None]
 [None]
 [None]]
[[ 497]
 [-356]
 [-345]
 [-270]
 [ -69]]
Error: dot
Error: dot
Error: dot
Error: dot
Error: dot
[[None]
 [None]
 [None]
 [None]
 [None]]
[[ 452]
 [-285]
 [-333]
 [-182]
 [-133]]
Error: dot
Error: dot
Error: dot
Error: dot
Error: dot
[[None]
 [None]
 [None]
 [None]
 [None]]
[[ 497]
 [-356]
 [-345]
 [-270]
 [ -69]]
Error: dot
Error: dot
Error: dot
Error: dot
Error: dot
[[None]
 [None]
 [None]
 [None]
 [None]]
[[ 452]
 [-285]
 [-333]
 [-182]
 [-133]]


In [15]:
def mat_mat_prod(m1, m2):
    if (not isinstance(m1, np.ndarray) or not isinstance(m2, np.ndarray) or
            m1.size == 0 or m1.shape[1] != m2.shape[0]):
        return None
    result = np.zeros((m1.shape[0], m2.shape[1]), dtype='int')
    for column in range(m2.shape[1]):
        result[:, column] = list(mat_vec_prod(m1, np.array(m2[:, column])))
    return result

In [16]:
# Matrix-matrix product
m1 = np.array([
    [-8, 8, -6, 14, 14, -9, -4],
    [2, -11, -2, -11, 14, -2, 14],
    [-13, -2, -5, 3, -8, -4, 13],
    [2, 13, -14, -15, -14, -15, 13],
    [2, -1, 12, 3, -7, -3, -6]])
Z = np.array([
    [-6, -1, -8, 7, -8],
    [7, 4, 0, -10, -10],
    [7, -13, 2, 2, -11],
    [3, 14, 7, 7, -4],
    [-1, -3, -8, -4, -14],
    [9, -14, 9, 12, -7],
    [-9, -4, -10, -3, 6]])
print(mat_mat_prod(m1, m2))
print(m1.dot(m2))
print(mat_mat_prod(m2, m1))
print(m2.dot(m1))

[[  45  414   -3 -202 -163]
 [-294 -244 -367  -79   62]
 [-107  140   13 -115  385]
 [-302  222 -302 -412  447]
 [ 108  -33  118   79  -67]]
[[  45  414   -3 -202 -163]
 [-294 -244 -367  -79   62]
 [-107  140   13 -115  385]
 [-302  222 -302 -412  447]
 [ 108  -33  118   79  -67]]
[[ 148   78 -116 -226  -76    7   45]
 [ -88 -108  -30  174  364  109  -42]
 [-126  232 -186  184  -51  -42  -92]
 [ -81  -49 -227 -208  112 -176  390]
 [  70    3  -60   13  162  149 -110]
 [-207  371 -323  106 -261 -248   83]
 [ 200  -53  226  -49 -102  156 -225]]
[[ 148   78 -116 -226  -76    7   45]
 [ -88 -108  -30  174  364  109  -42]
 [-126  232 -186  184  -51  -42  -92]
 [ -81  -49 -227 -208  112 -176  390]
 [  70    3  -60   13  162  149 -110]
 [-207  371 -323  106 -261 -248   83]
 [ 200  -53  226  -49 -102  156 -225]]
[[  45  414   -3 -202 -163]
 [-294 -244 -367  -79   62]
 [-107  140   13 -115  385]
 [-302  222 -302 -412  447]
 [ 108  -33  118   79  -67]]
[[  45  414   -3 -202 -163]
 [-294 -244 -36

In [17]:
def mse(x, y):
    if (not isinstance(x, np.ndarray) or not isinstance(y, np.ndarray) or
            x.size == 0 or y.size == 0 or x.shape[0] != y.shape[0] or
            x.ndim != 1 or y.ndim != 1):
        return None
    return mean_(np.subtract(x, y)**2)

In [18]:
# Mean squared error
x = np.array([0, 15, -9, 7, 12, 3, -21])
y = np.array([2, 14, -13, 5, 12, 4, -19])
print(mse(x, y))
print(mse(x, x))

4.285714285714286
0.0
4.285714285714286
0.0
4.285714285714286
0.0


In [19]:
def vec_mse(y, y_hat):
    if (not isinstance(y, np.ndarray)
            or not isinstance(y_hat, np.ndarray)
            or y.size == 0 or y_hat.size == 0
            or y.shape[0] != y_hat.shape[0]
            or y.size != y_hat.size):
        return None
    return dot(np.subtract(y_hat, y), np.subtract(y_hat, y)) / y.size

In [20]:
# Vectorized Mean Squared Error
print(vec_mse(X, Y))
print(vec_mse(X, X))

4.285714285714286
0.0
4.285714285714286
0.0
4.285714285714286
0.0


In [21]:
def linear_mse(x, y, theta):
    if (not isinstance(x, np.ndarray) or not isinstance(y, np.ndarray)
            or not isinstance(theta, np.ndarray) or x.size == 0 or y.size == 0
            or theta.size == 0 or len(y.shape) != 1 or len(theta.shape) != 1
            or x.shape[0] != y.size or x.shape[1] != theta.size):
        return None
    result = 0.0
    h = np.zeros(x.shape[0])
    for row in range(x.shape[0]):
        h[row] = dot(x[row], theta)
    return mse(y, h)

In [22]:
# Mean squared error as linear cost function
X = np.array([
    [-6, -7, -9],
    [13, -2, 14],
    [-7, 14, -1],
    [-8, -4, 6],
    [-5, -9, 6],
    [1, -5, 11],
    [9, -11, 8]])
Y = np.array([2, 14, -13, 5, 12, 4, -19])
Z = np.array([3, 0.5, -6])
W = np.array([0, 0, 0])

print(linear_mse(X, Y, Z))
print(linear_mse(X, Y, W))

2641.0
130.71428571428572
2641.0
130.71428571428572
2641.0
130.71428571428572


In [23]:
def vec_linear_mse(x, y, theta):
    if (not isinstance(x, np.ndarray) or not isinstance(y, np.ndarray)
            or not isinstance(theta, np.ndarray) or x.size == 0 or y.size == 0
            or theta.size == 0 or len(y.shape) != 1 or len(theta.shape) != 1
            or x.shape[0] != y.size or x.shape[1] != theta.size):
        return None
    h = np.zeros(x.shape[0])
    for row in range(x.shape[0]):
        h[row] = dot(x[row], theta)
    return dot(np.subtract(y, h), np.subtract(y, h)) / y.size

In [24]:
# Vectorized Mean squared error as linear cost function
print(vec_linear_mse(X, Y, Z))
print(vec_linear_mse(X, Y, W))

2641.0
130.71428571428572
2641.0
130.71428571428572
2641.0
130.71428571428572


In [25]:
def gradient(x, y, theta):
    if (not isinstance(x, np.ndarray) or not isinstance(y, np.ndarray)
            or not isinstance(theta, np.ndarray) or x.size == 0 or y.size == 0
            or theta.size == 0 or len(y.shape) != 1 or len(theta.shape) != 1
            or x.shape[0] != y.size or x.shape[1] != theta.size):
        return None
    h = np.zeros(x.shape[0])
    for row in range(x.shape[0]):
        h[row] = dot(x[row], theta)
    result = np.zeros(x.shape[1])
    for column in range(x.shape[1]):
        for row in range(x.shape[0]):
            result[column] += (h[row] - y[row]) * x[row][column] / x.shape[0]
    return result

In [26]:
# Linear Gradient - iterative version
print(gradient(X, Y, Z))
print(gradient(X, Y, W))
print(gradient(X, X.dot(Z), Z))

[ -37.35714286  183.14285714 -393.        ]
[  0.85714286  23.28571429 -26.42857143]
[0. 0. 0.]
[ -37.35714286  183.14285714 -393.        ]
[  0.85714286  23.28571429 -26.42857143]
[0. 0. 0.]
[ -37.35714286  183.14285714 -393.        ]
[  0.85714286  23.28571429 -26.42857143]
[0. 0. 0.]


In [27]:
def vec_gradient(x, y, theta):
    if (not isinstance(x, np.ndarray) or not isinstance(y, np.ndarray)
            or not isinstance(theta, np.ndarray) or x.size == 0 or y.size == 0
            or theta.size == 0 or y.ndim != 1 or theta.ndim != 1
            or x.shape[0] != y.size or x.shape[1] != theta.size):
        return None
    h = np.zeros(x.shape[0])
    for row in range(x.shape[0]):
        h[row] = dot(x[row], theta)
    result = mat_vec_prod(x.transpose(), np.subtract(h, y)) / x.shape[0]
    return result.reshape(1, x.shape[1])

In [28]:
# Linear Gradient - vectorized version
print(vec_gradient(X, Y, Z))
print(vec_gradient(X, Y, W))
print(vec_gradient(X, X.dot(Z), Z))

[[ -37.35714286  183.14285714 -393.        ]][[ -37.35714286  183.14285714 -393.        ]][[ -37.35714286  183.14285714 -393.        ]]
[[  0.85714286  23.28571429 -26.42857143]]
[[0. 0. 0.]]

[[  0.85714286  23.28571429 -26.42857143]]
[[0. 0. 0.]]

[[  0.85714286  23.28571429 -26.42857143]]
[[0. 0. 0.]]


In [29]:
def predict_(theta, X):
    if (not isinstance(X, np.ndarray) or not isinstance(theta, np.ndarray)
            or X.size == 0 or theta.size == 0 or theta.ndim != 1):
        return None
    if theta.shape[0] - 1 != X.shape[1]:
        print("Incompatible dimension match between X and theta.")
        return None
    X = np.insert(X, 0, 1, axis=1)
    return mat_vec_prod(X, theta)

In [30]:
# Hypothesis function
X1 = np.array([[0.], [1.], [2.], [3.], [4.]])
theta1 = np.array([[2.], [4.]])
print(predict_(theta1, X1))
X2 = np.array([[1], [2], [3], [5], [8]])
theta2 = np.array([[2.]])
print(predict_(theta2, X2))
X3 = np.array([[0.2, 2., 20.], [0.4, 4., 40.], [0.6, 6., 60.], [0.8, 8., 80.]])
theta3 = np.array([[0.05], [1.], [1.], [1.]])
print(predict_(theta3, X3))

None
None
None
None
None
None
None
None
None


In [31]:
def cost_elem_(theta, X, Y):
    if (not isinstance(X, np.ndarray) or not isinstance(theta, np.ndarray)
            or X.size == 0 or theta.size == 0 or theta.ndim != 1):
        return None
    M = X.shape[0]
    J_elem = np.zeros((M, 1))
    for i in range(len(J_elem)):
        J_elem[i] = (1/(2*M))*((np.subtract(predict_(theta, X), Y)[i])**2)
    return J_elem

def cost_(theta, X, Y):
    M = X.shape[0]
    J_elem = np.zeros((M, 1))
    for i in range(len(J_elem)):
        J_elem[i] = (1/(2*M))*((np.subtract(predict_(theta, X), Y)[i])**2)
    J_value = 0.0
    return J_value

In [32]:
# Cost function
X1 = np.array([[0.], [1.], [2.], [3.], [4.]])
theta1 = np.array([[2.], [4.]])
Y1 = np.array([[2.], [7.], [12.], [17.], [22.]])
print(cost_elem_(theta1, X1, Y1))
print(cost_(theta1, X1, Y1))
X2 = np.array([[0.2, 2., 20.], [0.4, 4., 40.], [0.6, 6., 60.], [0.8, 8., 80.]])
theta2 = np.array([[0.05], [1.], [1.], [1.]])
Y2 = np.array([[19.], [42.], [67.], [93.]])
print(cost_elem_(theta2, X2, Y2))
print(cost_(theta2, X2, Y2))

None
None
None


TypeError: unsupported operand type(s) for -: 'NoneType' and 'float'

TypeError: unsupported operand type(s) for -: 'NoneType' and 'float'

TypeError: unsupported operand type(s) for -: 'NoneType' and 'float'

In [ ]:
#hide
from nbdev.showdoc import *