In [1]:
# default_exp core

# 42AI Machine Learning Bootcamp

> API details.

In [2]:
import numpy as np

In [3]:
def sum_(x, f):
    if not isinstance(x, np.ndarray) or x.size == 0 or x.ndim != 1 or not callable(f):
        return None
    result = 0.0
    for element in x:
        result += f(element)
    return result

In [4]:
# Sum
x = np.array([0, 15, -9, 7, 12, 3, -21])
print(sum_(x, lambda x: x))
print(sum_(x, lambda x: x**2))

7.0
949.0


In [5]:
def mean_(x):
    if not isinstance(x, np.ndarray) or x.size == 0 or x.ndim != 1:
        return None
    return sum_(x, lambda x: x) / x.size

In [6]:
# Mean
x = np.array([0, 15, -9, 7, 12, 3, -21])
print(mean_(x))
print(mean_(x ** 2))

1.0
135.57142857142858


In [7]:
def variance(x):
    if not isinstance(x, np.ndarray) or x.size == 0 or x.ndim != 1:
        return None
    return mean_((x - mean_(x))**2)

In [8]:
# Variance
x = np.array([0, 15, -9, 7, 12, 3, -21])
print(variance(x))
print(np.var(x))

print(variance(x/2))
print(np.var(x/2))

134.57142857142858
134.57142857142858
33.642857142857146
33.642857142857146


In [9]:
from math import sqrt


def std(x):
    if not isinstance(x, np.ndarray) or x.size == 0 or x.ndim != 1:
        return None
    return sqrt((variance(x)))

In [10]:
# Standard deviation
x = np.array([0, 15, -9, 7, 12, 3, -21])
y = np.array([2, 14, -13, 5, 12, 4, -19])

print(std(x))
print(np.std(x))

print(std(y))
print(np.std(y))

11.600492600378166
11.600492600378166
11.410700312980492
11.410700312980492


In [11]:
def dot(x, y):
    if (not isinstance(x, np.ndarray) or not isinstance(y, np.ndarray) or x.size == 0 
        or y.size == 0 or x.size != y.size or x.ndim > 1 or y.ndim > 1):
        print("Error: dot")
        return None
    result = 0
    for i in range(x.size):
        result += x[i] * y[i]
    return result

In [12]:
# Dot product
x = np.array([0, 15, -9, 7, 12, 3, -21])
y = np.array([2, 14, -13, 5, 12, 4, -19])

print(dot(x, y))
print(np.dot(x, y))

print(dot(x, x))
print(np.dot(x, x))

print(dot(y, y))
print(np.dot(y, y))

917
917
949
949
915
915


In [13]:
def mat_vec_prod(m, x):
    if (not isinstance(m, np.ndarray) or not isinstance(x, np.ndarray) or
            m.size == 0 or m.shape[1] != x.size):
        print("Error: mat_vec_prod")
        return None
    result = np.array([], dtype='int')
    for row in m:
        result = np.append(result, dot(x, row))
    return result.reshape((m.shape[0], 1))

In [14]:
# Matrix-vector product
m = np.array([
    [-8, 8, -6, 14, 14, -9, -4],
    [2, -11, -2, -11, 14, -2, 14],
    [-13, -2, -5, 3, -8, -4, 13],
    [2, 13, -14, -15, -14, -15, 13],
    [2, -1, 12, 3, -7, -3, -6]])
x = np.array([0, 15, -9, 7, 12, 3, -21])
y = np.array([2, 14, -13, 5, 12, 4, -19])

print(mat_vec_prod(m, x))
print(m.dot(x))

print(mat_vec_prod(m, y))
print(m.dot(y))

[[ 497]
 [-356]
 [-345]
 [-270]
 [ -69]]
[ 497 -356 -345 -270  -69]
[[ 452]
 [-285]
 [-333]
 [-182]
 [-133]]
[ 452 -285 -333 -182 -133]


In [15]:
def mat_mat_prod(m1, m2):
    if (not isinstance(m1, np.ndarray) or not isinstance(m2, np.ndarray) or
            m1.size == 0 or m1.shape[1] != m2.shape[0]):
        return None
    result = np.zeros((m1.shape[0], m2.shape[1]), dtype='int')
    for column in range(m2.shape[1]):
        result[:, column] = list(mat_vec_prod(m1, np.array(m2[:, column])))
    return result

In [16]:
# Matrix-matrix product
m1 = np.array([
    [-8, 8, -6, 14, 14, -9, -4],
    [2, -11, -2, -11, 14, -2, 14],
    [-13, -2, -5, 3, -8, -4, 13],
    [2, 13, -14, -15, -14, -15, 13],
    [2, -1, 12, 3, -7, -3, -6]])
m2 = np.array([
    [-6, -1, -8, 7, -8],
    [7, 4, 0, -10, -10],
    [7, -13, 2, 2, -11],
    [3, 14, 7, 7, -4],
    [-1, -3, -8, -4, -14],
    [9, -14, 9, 12, -7],
    [-9, -4, -10, -3, 6]])
print(mat_mat_prod(m1, m2))
print(m1.dot(m2))
print(mat_mat_prod(m2, m1))
print(m2.dot(m1))

[[  45  414   -3 -202 -163]
 [-294 -244 -367  -79   62]
 [-107  140   13 -115  385]
 [-302  222 -302 -412  447]
 [ 108  -33  118   79  -67]]
[[  45  414   -3 -202 -163]
 [-294 -244 -367  -79   62]
 [-107  140   13 -115  385]
 [-302  222 -302 -412  447]
 [ 108  -33  118   79  -67]]
[[ 148   78 -116 -226  -76    7   45]
 [ -88 -108  -30  174  364  109  -42]
 [-126  232 -186  184  -51  -42  -92]
 [ -81  -49 -227 -208  112 -176  390]
 [  70    3  -60   13  162  149 -110]
 [-207  371 -323  106 -261 -248   83]
 [ 200  -53  226  -49 -102  156 -225]]
[[ 148   78 -116 -226  -76    7   45]
 [ -88 -108  -30  174  364  109  -42]
 [-126  232 -186  184  -51  -42  -92]
 [ -81  -49 -227 -208  112 -176  390]
 [  70    3  -60   13  162  149 -110]
 [-207  371 -323  106 -261 -248   83]
 [ 200  -53  226  -49 -102  156 -225]]


In [17]:
def mse(x, y):
    if (not isinstance(x, np.ndarray) or not isinstance(y, np.ndarray) or
            x.size == 0 or y.size == 0 or x.shape[0] != y.shape[0] or
            x.ndim != 1 or y.ndim != 1):
        return None
    return mean_(np.subtract(x, y)**2)

In [18]:
# Mean squared error
x = np.array([0, 15, -9, 7, 12, 3, -21])
y = np.array([2, 14, -13, 5, 12, 4, -19])
print(mse(x, y))
print(mse(x, x))

4.285714285714286
0.0


In [19]:
def vec_mse(y, y_hat):
    if (not isinstance(y, np.ndarray)
            or not isinstance(y_hat, np.ndarray)
            or y.size == 0 or y_hat.size == 0
            or y.shape[0] != y_hat.shape[0]
            or y.size != y_hat.size):
        return None
    return dot(np.subtract(y_hat, y), np.subtract(y_hat, y)) / y.size

In [20]:
# Vectorized Mean Squared Error
print(vec_mse(x, y))
print(vec_mse(x, x))

4.285714285714286
0.0


In [21]:
def linear_mse(m, y, theta):
    if (not isinstance(m, np.ndarray) or not isinstance(y, np.ndarray) or not isinstance(theta, np.ndarray) 
        or m.size == 0 or y.size == 0 or theta.size == 0
        or len(y.shape) != 1 or len(theta.shape) != 1
        or m.shape[0] != y.size or m.shape[1] != theta.size):
        return None
    result = 0.0
    h = np.zeros(m.shape[0])
    for row in range(m.shape[0]):
        h[row] = dot(m[row], theta)
    return mse(y, h)

In [22]:
# Mean squared error as linear cost function
m = np.array([
    [-6, -7, -9],
    [13, -2, 14],
    [-7, 14, -1],
    [-8, -4, 6],
    [-5, -9, 6],
    [1, -5, 11],
    [9, -11, 8]])
y = np.array([2, 14, -13, 5, 12, 4, -19])
theta1 = np.array([3, 0.5, -6])
theta2 = np.array([0, 0, 0])

print(linear_mse(m, y, theta1))
print(linear_mse(m, y, theta2))

2641.0
130.71428571428572


In [23]:
def vec_linear_mse(m, y, theta):
    if (not isinstance(m, np.ndarray) or not isinstance(y, np.ndarray)
            or not isinstance(theta, np.ndarray) or m.size == 0 or y.size == 0
            or theta.size == 0 or len(y.shape) != 1 or len(theta.shape) != 1
            or m.shape[0] != y.size or m.shape[1] != theta.size):
        return None
    h = np.zeros(m.shape[0])
    for row in range(m.shape[0]):
        h[row] = dot(m[row], theta)
    return dot(np.subtract(y, h), np.subtract(y, h)) / y.size

In [24]:
# Vectorized Mean squared error as linear cost function
print(vec_linear_mse(m, y, theta1))
print(vec_linear_mse(m, y, theta2))

2641.0
130.71428571428572


In [25]:
def gradient(m, y, theta):
    if (not isinstance(m, np.ndarray) or not isinstance(y, np.ndarray)
            or not isinstance(theta, np.ndarray) or m.size == 0 or y.size == 0
            or theta.size == 0 or len(y.shape) != 1 or len(theta.shape) != 1
            or m.shape[0] != y.size or m.shape[1] != theta.size):
        return None
    training_examples = m.shape[0]
    features = m.shape[1]
    h = np.zeros(training_examples)
    for row in range(training_examples):
        h[row] = dot(m[row], theta)
    result = np.zeros(features)
    for column in range(features):
        for row in range(training_examples):
            result[column] += (h[row] - y[row]) * m[row][column] / training_examples
    return result

In [26]:
# Linear Gradient - iterative version
print(gradient(m, y, theta1))
print(gradient(m, y, theta2))
print(gradient(m, m.dot(theta1), theta1))

[ -37.35714286  183.14285714 -393.        ]
[  0.85714286  23.28571429 -26.42857143]
[0. 0. 0.]


In [27]:
def vec_gradient(m, y, theta):
    if (not isinstance(m, np.ndarray) or not isinstance(y, np.ndarray)
            or not isinstance(theta, np.ndarray) or m.size == 0 or y.size == 0
            or theta.size == 0 or y.ndim != 1 or theta.ndim != 1
            or m.shape[0] != y.size or m.shape[1] != theta.size):
        return None
    h = np.zeros(m.shape[0])
    for row in range(m.shape[0]):
        h[row] = dot(m[row], theta)
    result = mat_vec_prod(m.transpose(), np.subtract(h, y)) / m.shape[0]
    return result.reshape(m.shape[1])

In [28]:
# Linear Gradient - vectorized version
print(vec_gradient(m, y, theta1))
print(vec_gradient(m, y, theta2))
print(vec_gradient(m, m.dot(theta1), theta1))

[ -37.35714286  183.14285714 -393.        ]
[  0.85714286  23.28571429 -26.42857143]
[0. 0. 0.]


In [29]:
def predict_(theta, m):
    if (not isinstance(m, np.ndarray) or not isinstance(theta, np.ndarray)
            or m.size == 0 or theta.size == 0 or theta.ndim != 1):
        return None
    if theta.size - 1 != m.shape[1]:
        print("Incompatible dimension match between X and theta.")
        return None
    m = np.insert(m, 0, 1, axis=1)
    return mat_vec_prod(m, theta)

In [30]:
# Hypothesis function
m1 = np.array([[0.], [1.], [2.], [3.], [4.]])
theta1 = np.array([2., 4.])
print(predict_(theta1, m1))
m2 = np.array([[1], [2], [3], [5], [8]])
theta2 = np.array([2.])
print(predict_(theta2, m2))
m3 = np.array([[0.2, 2., 20.], [0.4, 4., 40.], [0.6, 6., 60.], [0.8, 8., 80.]])
theta3 = np.array([0.05, 1., 1., 1.])
print(predict_(theta3, m3))

[[ 2.]
 [ 6.]
 [10.]
 [14.]
 [18.]]
Incompatible dimension match between X and theta.
None
[[22.25]
 [44.45]
 [66.65]
 [88.85]]


In [31]:
def cost_elem_(theta, m, y):
    if (not isinstance(m, np.ndarray) or not isinstance(theta, np.ndarray)
            or m.size == 0 or theta.size == 0 or theta.ndim != 1):
        return None
    M = m.shape[0]
    J_elem = np.zeros((M, 1))
    for i in range(len(J_elem)):
        J_elem[i] = (1/(2*M))*((np.subtract(predict_(theta, m), y)[i])**2)
    return J_elem

def cost_(theta, m, y):
    M = m.shape[0]
    J_elem = np.zeros(M)
    for i in range(M):
        J_elem[i] = (1/(2*M))*((np.subtract(predict_(theta, m), y)[i])**2)
    J_value = sum_(J_elem, lambda x : x)
    return J_value

In [32]:
# Cost function
X1 = np.array([[0.], [1.], [2.], [3.], [4.]])
theta1 = np.array([2., 4.])
Y1 = np.array([[2.], [7.], [12.], [17.], [22.]])
print(cost_elem_(theta1, X1, Y1))
print(cost_(theta1, X1, Y1))
X2 = np.array([[0.2, 2., 20.], [0.4, 4., 40.], [0.6, 6., 60.], [0.8, 8., 80.]])
theta2 = np.array([0.05, 1., 1., 1.])
Y2 = np.array([[19.], [42.], [67.], [93.]])
print(cost_elem_(theta2, X2, Y2))
print(cost_(theta2, X2, Y2))

[[0. ]
 [0.1]
 [0.4]
 [0.9]
 [1.6]]
3.0
[[1.3203125]
 [0.7503125]
 [0.0153125]
 [2.1528125]]
4.238750000000007


In [37]:
def fit_(theta, m, y, alpha, n_cycle):
    return theta

In [38]:
m1 = np.array([[0.], [1.], [2.], [3.], [4.]])
y1 = np.array([2., 6., 10., 14., 18.])
theta1 = np.array([1., 1.])
theta1 = fit_(theta1, m1, y1, alpha=0.01, n_cycle=2000)
print(theta1)
#array([[2.0023..],[3.9991..]])
print(predict_(theta1, m1))
#array([2.0023..], [6.002..], [10.0007..], [13.99988..], [17.9990..])

m2 = np.array([[0.2, 2., 20.], [0.4, 4., 40.], [0.6, 6., 60.], [0.8, 8., 80.]])
y2 = np.array([19.6, -2.8, -25.2, -47.6])
theta2 = np.array([42., 1., 1., 1.])
theta2 = fit_(theta2, m2, y2, alpha=0.0005, n_cycle=42000)
print(theta2)
#array([[41.99..],[0.97..], [0.77..], [-1.20..]])
print(predict_(theta2, m2))
#array([[19.5937..], [-2.8021..], [-25.1999..], [-47.5978..]])

[1. 1.]
[[1.]
 [2.]
 [3.]
 [4.]
 [5.]]
[42.  1.  1.  1.]
[[ 64.2]
 [ 86.4]
 [108.6]
 [130.8]]


In [35]:
#hide
from nbdev.showdoc import *